---
- hosts: all
  vars:
    sudoers:
      - user1
      - user2
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add sudoers users to wheel group
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items: "{{ sudoers }}"

    - name: Glone from Git
      ansible.builtin.git:
        repo: 'https://github.com/Ashok-Karuppaiyan/systems.git'
        dest: /tmp/repo
    
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: https://github.com/Ashok-Karuppaiyan/systems/blob/main/ssh_keys/id_rsa.pub
      with_items: "{{ sudoers }}"