---
- hosts: all
  become: true
  tasks:
    - name: Update apt and install required system packages
        apt:
          pkg:
            - curl
            - vim
            - git
            - ufw
            - wget
            - telnet
            - tcptraceroute
          state: latest
          update_cache: true
